(defpackage #:cl-s3r.components.icon
  (:use #:cl)
  (:import-from #:cl-s3r.component #:define-component)
  (:import-from #:cl-s3r.components.icon.util #:size->css-dimension)
  (:import-from #:cl-s3r.components.fa-address-book #:fa-address-book)
  (:import-from #:cl-s3r.components.fa-address-card #:fa-address-card)
  (:import-from #:cl-s3r.components.fa-alarm-clock #:fa-alarm-clock)
  (:import-from #:cl-s3r.components.fa-angry #:fa-angry)
  (:import-from #:cl-s3r.components.fa-arrow-alt-circle-down #:fa-arrow-alt-circle-down)
  (:import-from #:cl-s3r.components.fa-arrow-alt-circle-left #:fa-arrow-alt-circle-left)
  (:import-from #:cl-s3r.components.fa-arrow-alt-circle-right #:fa-arrow-alt-circle-right)
  (:import-from #:cl-s3r.components.fa-arrow-alt-circle-up #:fa-arrow-alt-circle-up)
  (:import-from #:cl-s3r.components.fa-bar-chart #:fa-bar-chart)
  (:import-from #:cl-s3r.components.fa-bell-slash #:fa-bell-slash)
  (:import-from #:cl-s3r.components.fa-bell #:fa-bell)
  (:import-from #:cl-s3r.components.fa-bookmark #:fa-bookmark)
  (:import-from #:cl-s3r.components.fa-building #:fa-building)
  (:import-from #:cl-s3r.components.fa-calendar-alt #:fa-calendar-alt)
  (:import-from #:cl-s3r.components.fa-calendar-check #:fa-calendar-check)
  (:import-from #:cl-s3r.components.fa-calendar-days #:fa-calendar-days)
  (:import-from #:cl-s3r.components.fa-calendar-minus #:fa-calendar-minus)
  (:import-from #:cl-s3r.components.fa-calendar-plus #:fa-calendar-plus)
  (:import-from #:cl-s3r.components.fa-calendar #:fa-calendar)
  (:import-from #:cl-s3r.components.fa-calendar-times #:fa-calendar-times)
  (:import-from #:cl-s3r.components.fa-calendar-xmark #:fa-calendar-xmark)
  (:import-from #:cl-s3r.components.fa-camera-alt #:fa-camera-alt)
  (:import-from #:cl-s3r.components.fa-camera #:fa-camera)
  (:import-from #:cl-s3r.components.fa-caret-square-down #:fa-caret-square-down)
  (:import-from #:cl-s3r.components.fa-caret-square-left #:fa-caret-square-left)
  (:import-from #:cl-s3r.components.fa-caret-square-right #:fa-caret-square-right)
  (:import-from #:cl-s3r.components.fa-caret-square-up #:fa-caret-square-up)
  (:import-from #:cl-s3r.components.fa-chart-bar #:fa-chart-bar)
  (:import-from #:cl-s3r.components.fa-check-circle #:fa-check-circle)
  (:import-from #:cl-s3r.components.fa-check-square #:fa-check-square)
  (:import-from #:cl-s3r.components.fa-chess-bishop #:fa-chess-bishop)
  (:import-from #:cl-s3r.components.fa-chess-king #:fa-chess-king)
  (:import-from #:cl-s3r.components.fa-chess-knight #:fa-chess-knight)
  (:import-from #:cl-s3r.components.fa-chess-pawn #:fa-chess-pawn)
  (:import-from #:cl-s3r.components.fa-chess-queen #:fa-chess-queen)
  (:import-from #:cl-s3r.components.fa-chess-rook #:fa-chess-rook)
  (:import-from #:cl-s3r.components.fa-circle-check #:fa-circle-check)
  (:import-from #:cl-s3r.components.fa-circle-dot #:fa-circle-dot)
  (:import-from #:cl-s3r.components.fa-circle-down #:fa-circle-down)
  (:import-from #:cl-s3r.components.fa-circle-left #:fa-circle-left)
  (:import-from #:cl-s3r.components.fa-circle-pause #:fa-circle-pause)
  (:import-from #:cl-s3r.components.fa-circle-play #:fa-circle-play)
  (:import-from #:cl-s3r.components.fa-circle-question #:fa-circle-question)
  (:import-from #:cl-s3r.components.fa-circle-right #:fa-circle-right)
  (:import-from #:cl-s3r.components.fa-circle-stop #:fa-circle-stop)
  (:import-from #:cl-s3r.components.fa-circle #:fa-circle)
  (:import-from #:cl-s3r.components.fa-circle-up #:fa-circle-up)
  (:import-from #:cl-s3r.components.fa-circle-user #:fa-circle-user)
  (:import-from #:cl-s3r.components.fa-circle-xmark #:fa-circle-xmark)
  (:import-from #:cl-s3r.components.fa-clipboard #:fa-clipboard)
  (:import-from #:cl-s3r.components.fa-clock-four #:fa-clock-four)
  (:import-from #:cl-s3r.components.fa-clock #:fa-clock)
  (:import-from #:cl-s3r.components.fa-clone #:fa-clone)
  (:import-from #:cl-s3r.components.fa-closed-captioning #:fa-closed-captioning)
  (:import-from #:cl-s3r.components.fa-cloud #:fa-cloud)
  (:import-from #:cl-s3r.components.fa-comment-alt #:fa-comment-alt)
  (:import-from #:cl-s3r.components.fa-comment-dots #:fa-comment-dots)
  (:import-from #:cl-s3r.components.fa-commenting #:fa-commenting)
  (:import-from #:cl-s3r.components.fa-comments #:fa-comments)
  (:import-from #:cl-s3r.components.fa-comment #:fa-comment)
  (:import-from #:cl-s3r.components.fa-compass #:fa-compass)
  (:import-from #:cl-s3r.components.fa-contact-book #:fa-contact-book)
  (:import-from #:cl-s3r.components.fa-contact-card #:fa-contact-card)
  (:import-from #:cl-s3r.components.fa-copyright #:fa-copyright)
  (:import-from #:cl-s3r.components.fa-copy #:fa-copy)
  (:import-from #:cl-s3r.components.fa-credit-card-alt #:fa-credit-card-alt)
  (:import-from #:cl-s3r.components.fa-credit-card #:fa-credit-card)
  (:import-from #:cl-s3r.components.fa-dizzy #:fa-dizzy)
  (:import-from #:cl-s3r.components.fa-dot-circle #:fa-dot-circle)
  (:import-from #:cl-s3r.components.fa-drivers-license #:fa-drivers-license)
  (:import-from #:cl-s3r.components.fa-edit #:fa-edit)
  (:import-from #:cl-s3r.components.fa-envelope-open #:fa-envelope-open)
  (:import-from #:cl-s3r.components.fa-envelope #:fa-envelope)
  (:import-from #:cl-s3r.components.fa-eye-slash #:fa-eye-slash)
  (:import-from #:cl-s3r.components.fa-eye #:fa-eye)
  (:import-from #:cl-s3r.components.fa-face-angry #:fa-face-angry)
  (:import-from #:cl-s3r.components.fa-face-dizzy #:fa-face-dizzy)
  (:import-from #:cl-s3r.components.fa-face-flushed #:fa-face-flushed)
  (:import-from #:cl-s3r.components.fa-face-frown-open #:fa-face-frown-open)
  (:import-from #:cl-s3r.components.fa-face-frown #:fa-face-frown)
  (:import-from #:cl-s3r.components.fa-face-grimace #:fa-face-grimace)
  (:import-from #:cl-s3r.components.fa-face-grin-beam #:fa-face-grin-beam)
  (:import-from #:cl-s3r.components.fa-face-grin-beam-sweat #:fa-face-grin-beam-sweat)
  (:import-from #:cl-s3r.components.fa-face-grin-hearts #:fa-face-grin-hearts)
  (:import-from #:cl-s3r.components.fa-face-grin-squint #:fa-face-grin-squint)
  (:import-from #:cl-s3r.components.fa-face-grin-squint-tears #:fa-face-grin-squint-tears)
  (:import-from #:cl-s3r.components.fa-face-grin-stars #:fa-face-grin-stars)
  (:import-from #:cl-s3r.components.fa-face-grin #:fa-face-grin)
  (:import-from #:cl-s3r.components.fa-face-grin-tears #:fa-face-grin-tears)
  (:import-from #:cl-s3r.components.fa-face-grin-tongue-squint #:fa-face-grin-tongue-squint)
  (:import-from #:cl-s3r.components.fa-face-grin-tongue #:fa-face-grin-tongue)
  (:import-from #:cl-s3r.components.fa-face-grin-tongue-wink #:fa-face-grin-tongue-wink)
  (:import-from #:cl-s3r.components.fa-face-grin-wide #:fa-face-grin-wide)
  (:import-from #:cl-s3r.components.fa-face-grin-wink #:fa-face-grin-wink)
  (:import-from #:cl-s3r.components.fa-face-kiss-beam #:fa-face-kiss-beam)
  (:import-from #:cl-s3r.components.fa-face-kiss #:fa-face-kiss)
  (:import-from #:cl-s3r.components.fa-face-kiss-wink-heart #:fa-face-kiss-wink-heart)
  (:import-from #:cl-s3r.components.fa-face-laugh-beam #:fa-face-laugh-beam)
  (:import-from #:cl-s3r.components.fa-face-laugh-squint #:fa-face-laugh-squint)
  (:import-from #:cl-s3r.components.fa-face-laugh #:fa-face-laugh)
  (:import-from #:cl-s3r.components.fa-face-laugh-wink #:fa-face-laugh-wink)
  (:import-from #:cl-s3r.components.fa-face-meh-blank #:fa-face-meh-blank)
  (:import-from #:cl-s3r.components.fa-face-meh #:fa-face-meh)
  (:import-from #:cl-s3r.components.fa-face-rolling-eyes #:fa-face-rolling-eyes)
  (:import-from #:cl-s3r.components.fa-face-sad-cry #:fa-face-sad-cry)
  (:import-from #:cl-s3r.components.fa-face-sad-tear #:fa-face-sad-tear)
  (:import-from #:cl-s3r.components.fa-face-smile-beam #:fa-face-smile-beam)
  (:import-from #:cl-s3r.components.fa-face-smile #:fa-face-smile)
  (:import-from #:cl-s3r.components.fa-face-smile-wink #:fa-face-smile-wink)
  (:import-from #:cl-s3r.components.fa-face-surprise #:fa-face-surprise)
  (:import-from #:cl-s3r.components.fa-face-tired #:fa-face-tired)
  (:import-from #:cl-s3r.components.fa-file-alt #:fa-file-alt)
  (:import-from #:cl-s3r.components.fa-file-archive #:fa-file-archive)
  (:import-from #:cl-s3r.components.fa-file-audio #:fa-file-audio)
  (:import-from #:cl-s3r.components.fa-file-clipboard #:fa-file-clipboard)
  (:import-from #:cl-s3r.components.fa-file-code #:fa-file-code)
  (:import-from #:cl-s3r.components.fa-file-excel #:fa-file-excel)
  (:import-from #:cl-s3r.components.fa-file-image #:fa-file-image)
  (:import-from #:cl-s3r.components.fa-file-lines #:fa-file-lines)
  (:import-from #:cl-s3r.components.fa-file-pdf #:fa-file-pdf)
  (:import-from #:cl-s3r.components.fa-file-powerpoint #:fa-file-powerpoint)
  (:import-from #:cl-s3r.components.fa-file #:fa-file)
  (:import-from #:cl-s3r.components.fa-file-text #:fa-file-text)
  (:import-from #:cl-s3r.components.fa-file-video #:fa-file-video)
  (:import-from #:cl-s3r.components.fa-file-word #:fa-file-word)
  (:import-from #:cl-s3r.components.fa-file-zipper #:fa-file-zipper)
  (:import-from #:cl-s3r.components.fa-flag #:fa-flag)
  (:import-from #:cl-s3r.components.fa-floppy-disk #:fa-floppy-disk)
  (:import-from #:cl-s3r.components.fa-flushed #:fa-flushed)
  (:import-from #:cl-s3r.components.fa-folder-blank #:fa-folder-blank)
  (:import-from #:cl-s3r.components.fa-folder-closed #:fa-folder-closed)
  (:import-from #:cl-s3r.components.fa-folder-open #:fa-folder-open)
  (:import-from #:cl-s3r.components.fa-folder #:fa-folder)
  (:import-from #:cl-s3r.components.fa-font-awesome-flag #:fa-font-awesome-flag)
  (:import-from #:cl-s3r.components.fa-font-awesome-logo-full #:fa-font-awesome-logo-full)
  (:import-from #:cl-s3r.components.fa-font-awesome #:fa-font-awesome)
  (:import-from #:cl-s3r.components.fa-frown-open #:fa-frown-open)
  (:import-from #:cl-s3r.components.fa-frown #:fa-frown)
  (:import-from #:cl-s3r.components.fa-futbol-ball #:fa-futbol-ball)
  (:import-from #:cl-s3r.components.fa-futbol #:fa-futbol)
  (:import-from #:cl-s3r.components.fa-gem #:fa-gem)
  (:import-from #:cl-s3r.components.fa-grimace #:fa-grimace)
  (:import-from #:cl-s3r.components.fa-grin-alt #:fa-grin-alt)
  (:import-from #:cl-s3r.components.fa-grin-beam #:fa-grin-beam)
  (:import-from #:cl-s3r.components.fa-grin-beam-sweat #:fa-grin-beam-sweat)
  (:import-from #:cl-s3r.components.fa-grin-hearts #:fa-grin-hearts)
  (:import-from #:cl-s3r.components.fa-grin-squint #:fa-grin-squint)
  (:import-from #:cl-s3r.components.fa-grin-squint-tears #:fa-grin-squint-tears)
  (:import-from #:cl-s3r.components.fa-grin-stars #:fa-grin-stars)
  (:import-from #:cl-s3r.components.fa-grin #:fa-grin)
  (:import-from #:cl-s3r.components.fa-grin-tears #:fa-grin-tears)
  (:import-from #:cl-s3r.components.fa-grin-tongue-squint #:fa-grin-tongue-squint)
  (:import-from #:cl-s3r.components.fa-grin-tongue #:fa-grin-tongue)
  (:import-from #:cl-s3r.components.fa-grin-tongue-wink #:fa-grin-tongue-wink)
  (:import-from #:cl-s3r.components.fa-grin-wink #:fa-grin-wink)
  (:import-from #:cl-s3r.components.fa-hand-back-fist #:fa-hand-back-fist)
  (:import-from #:cl-s3r.components.fa-hand-lizard #:fa-hand-lizard)
  (:import-from #:cl-s3r.components.fa-hand-paper #:fa-hand-paper)
  (:import-from #:cl-s3r.components.fa-hand-peace #:fa-hand-peace)
  (:import-from #:cl-s3r.components.fa-hand-point-down #:fa-hand-point-down)
  (:import-from #:cl-s3r.components.fa-hand-pointer #:fa-hand-pointer)
  (:import-from #:cl-s3r.components.fa-hand-point-left #:fa-hand-point-left)
  (:import-from #:cl-s3r.components.fa-hand-point-right #:fa-hand-point-right)
  (:import-from #:cl-s3r.components.fa-hand-point-up #:fa-hand-point-up)
  (:import-from #:cl-s3r.components.fa-hand-rock #:fa-hand-rock)
  (:import-from #:cl-s3r.components.fa-hand-scissors #:fa-hand-scissors)
  (:import-from #:cl-s3r.components.fa-handshake-alt #:fa-handshake-alt)
  (:import-from #:cl-s3r.components.fa-handshake-simple #:fa-handshake-simple)
  (:import-from #:cl-s3r.components.fa-handshake #:fa-handshake)
  (:import-from #:cl-s3r.components.fa-hand-spock #:fa-hand-spock)
  (:import-from #:cl-s3r.components.fa-hand #:fa-hand)
  (:import-from #:cl-s3r.components.fa-hard-drive #:fa-hard-drive)
  (:import-from #:cl-s3r.components.fa-hdd #:fa-hdd)
  (:import-from #:cl-s3r.components.fa-headphones-alt #:fa-headphones-alt)
  (:import-from #:cl-s3r.components.fa-headphones-simple #:fa-headphones-simple)
  (:import-from #:cl-s3r.components.fa-headphones #:fa-headphones)
  (:import-from #:cl-s3r.components.fa-heart #:fa-heart)
  (:import-from #:cl-s3r.components.fa-home-alt #:fa-home-alt)
  (:import-from #:cl-s3r.components.fa-home-lg-alt #:fa-home-lg-alt)
  (:import-from #:cl-s3r.components.fa-home #:fa-home)
  (:import-from #:cl-s3r.components.fa-hospital-alt #:fa-hospital-alt)
  (:import-from #:cl-s3r.components.fa-hospital #:fa-hospital)
  (:import-from #:cl-s3r.components.fa-hospital-wide #:fa-hospital-wide)
  (:import-from #:cl-s3r.components.fa-hourglass-2 #:fa-hourglass-2)
  (:import-from #:cl-s3r.components.fa-hourglass-empty #:fa-hourglass-empty)
  (:import-from #:cl-s3r.components.fa-hourglass-half #:fa-hourglass-half)
  (:import-from #:cl-s3r.components.fa-hourglass #:fa-hourglass)
  (:import-from #:cl-s3r.components.fa-house #:fa-house)
  (:import-from #:cl-s3r.components.fa-id-badge #:fa-id-badge)
  (:import-from #:cl-s3r.components.fa-id-card #:fa-id-card)
  (:import-from #:cl-s3r.components.fa-images #:fa-images)
  (:import-from #:cl-s3r.components.fa-image #:fa-image)
  (:import-from #:cl-s3r.components.fa-keyboard #:fa-keyboard)
  (:import-from #:cl-s3r.components.fa-kiss-beam #:fa-kiss-beam)
  (:import-from #:cl-s3r.components.fa-kiss #:fa-kiss)
  (:import-from #:cl-s3r.components.fa-kiss-wink-heart #:fa-kiss-wink-heart)
  (:import-from #:cl-s3r.components.fa-laugh-beam #:fa-laugh-beam)
  (:import-from #:cl-s3r.components.fa-laugh-squint #:fa-laugh-squint)
  (:import-from #:cl-s3r.components.fa-laugh #:fa-laugh)
  (:import-from #:cl-s3r.components.fa-laugh-wink #:fa-laugh-wink)
  (:import-from #:cl-s3r.components.fa-lemon #:fa-lemon)
  (:import-from #:cl-s3r.components.fa-life-ring #:fa-life-ring)
  (:import-from #:cl-s3r.components.fa-lightbulb #:fa-lightbulb)
  (:import-from #:cl-s3r.components.fa-list-alt #:fa-list-alt)
  (:import-from #:cl-s3r.components.fa-map #:fa-map)
  (:import-from #:cl-s3r.components.fa-meh-blank #:fa-meh-blank)
  (:import-from #:cl-s3r.components.fa-meh-rolling-eyes #:fa-meh-rolling-eyes)
  (:import-from #:cl-s3r.components.fa-meh #:fa-meh)
  (:import-from #:cl-s3r.components.fa-message #:fa-message)
  (:import-from #:cl-s3r.components.fa-minus-square #:fa-minus-square)
  (:import-from #:cl-s3r.components.fa-money-bill-1 #:fa-money-bill-1)
  (:import-from #:cl-s3r.components.fa-money-bill-alt #:fa-money-bill-alt)
  (:import-from #:cl-s3r.components.fa-moon #:fa-moon)
  (:import-from #:cl-s3r.components.fa-newspaper #:fa-newspaper)
  (:import-from #:cl-s3r.components.fa-note-sticky #:fa-note-sticky)
  (:import-from #:cl-s3r.components.fa-object-group #:fa-object-group)
  (:import-from #:cl-s3r.components.fa-object-ungroup #:fa-object-ungroup)
  (:import-from #:cl-s3r.components.fa-paper-plane #:fa-paper-plane)
  (:import-from #:cl-s3r.components.fa-paste #:fa-paste)
  (:import-from #:cl-s3r.components.fa-pause-circle #:fa-pause-circle)
  (:import-from #:cl-s3r.components.fa-pen-to-square #:fa-pen-to-square)
  (:import-from #:cl-s3r.components.fa-play-circle #:fa-play-circle)
  (:import-from #:cl-s3r.components.fa-plus-square #:fa-plus-square)
  (:import-from #:cl-s3r.components.fa-question-circle #:fa-question-circle)
  (:import-from #:cl-s3r.components.fa-rectangle-list #:fa-rectangle-list)
  (:import-from #:cl-s3r.components.fa-rectangle-times #:fa-rectangle-times)
  (:import-from #:cl-s3r.components.fa-rectangle-xmark #:fa-rectangle-xmark)
  (:import-from #:cl-s3r.components.fa-registered #:fa-registered)
  (:import-from #:cl-s3r.components.fa-sad-cry #:fa-sad-cry)
  (:import-from #:cl-s3r.components.fa-sad-tear #:fa-sad-tear)
  (:import-from #:cl-s3r.components.fa-save #:fa-save)
  (:import-from #:cl-s3r.components.fa-share-from-square #:fa-share-from-square)
  (:import-from #:cl-s3r.components.fa-share-square #:fa-share-square)
  (:import-from #:cl-s3r.components.fa-smile-beam #:fa-smile-beam)
  (:import-from #:cl-s3r.components.fa-smile #:fa-smile)
  (:import-from #:cl-s3r.components.fa-smile-wink #:fa-smile-wink)
  (:import-from #:cl-s3r.components.fa-snowflake #:fa-snowflake)
  (:import-from #:cl-s3r.components.fa-soccer-ball #:fa-soccer-ball)
  (:import-from #:cl-s3r.components.fa-square-caret-down #:fa-square-caret-down)
  (:import-from #:cl-s3r.components.fa-square-caret-left #:fa-square-caret-left)
  (:import-from #:cl-s3r.components.fa-square-caret-right #:fa-square-caret-right)
  (:import-from #:cl-s3r.components.fa-square-caret-up #:fa-square-caret-up)
  (:import-from #:cl-s3r.components.fa-square-check #:fa-square-check)
  (:import-from #:cl-s3r.components.fa-square-full #:fa-square-full)
  (:import-from #:cl-s3r.components.fa-square-minus #:fa-square-minus)
  (:import-from #:cl-s3r.components.fa-square-plus #:fa-square-plus)
  (:import-from #:cl-s3r.components.fa-square #:fa-square)
  (:import-from #:cl-s3r.components.fa-star-half-alt #:fa-star-half-alt)
  (:import-from #:cl-s3r.components.fa-star-half-stroke #:fa-star-half-stroke)
  (:import-from #:cl-s3r.components.fa-star-half #:fa-star-half)
  (:import-from #:cl-s3r.components.fa-star #:fa-star)
  (:import-from #:cl-s3r.components.fa-sticky-note #:fa-sticky-note)
  (:import-from #:cl-s3r.components.fa-stop-circle #:fa-stop-circle)
  (:import-from #:cl-s3r.components.fa-sun #:fa-sun)
  (:import-from #:cl-s3r.components.fa-surprise #:fa-surprise)
  (:import-from #:cl-s3r.components.fa-thumbs-down #:fa-thumbs-down)
  (:import-from #:cl-s3r.components.fa-thumbs-up #:fa-thumbs-up)
  (:import-from #:cl-s3r.components.fa-times-circle #:fa-times-circle)
  (:import-from #:cl-s3r.components.fa-times-rectangle #:fa-times-rectangle)
  (:import-from #:cl-s3r.components.fa-tired #:fa-tired)
  (:import-from #:cl-s3r.components.fa-trash-alt #:fa-trash-alt)
  (:import-from #:cl-s3r.components.fa-trash-can #:fa-trash-can)
  (:import-from #:cl-s3r.components.fa-truck #:fa-truck)
  (:import-from #:cl-s3r.components.fa-user-alt #:fa-user-alt)
  (:import-from #:cl-s3r.components.fa-user-circle #:fa-user-circle)
  (:import-from #:cl-s3r.components.fa-user-large #:fa-user-large)
  (:import-from #:cl-s3r.components.fa-user #:fa-user)
  (:import-from #:cl-s3r.components.fa-vcard #:fa-vcard)
  (:import-from #:cl-s3r.components.fa-window-close #:fa-window-close)
  (:import-from #:cl-s3r.components.fa-window-maximize #:fa-window-maximize)
  (:import-from #:cl-s3r.components.fa-window-minimize #:fa-window-minimize)
  (:import-from #:cl-s3r.components.fa-window-restore #:fa-window-restore)
  (:import-from #:cl-s3r.components.fa-xmark-circle #:fa-xmark-circle)
  (:export #:icon))

(in-package #:cl-s3r.components.icon)

(define-component icon (&key value color size onclick)
  (let* ((dim (size->css-dimension (or size "M")))
         (inner (cond
      ((string= value "fa-address-book")
       `(fa-address-book (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-address-card")
       `(fa-address-card (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-alarm-clock")
       `(fa-alarm-clock (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-angry")
       `(fa-angry (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-arrow-alt-circle-down")
       `(fa-arrow-alt-circle-down (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-arrow-alt-circle-left")
       `(fa-arrow-alt-circle-left (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-arrow-alt-circle-right")
       `(fa-arrow-alt-circle-right (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-arrow-alt-circle-up")
       `(fa-arrow-alt-circle-up (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-bar-chart")
       `(fa-bar-chart (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-bell-slash")
       `(fa-bell-slash (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-bell")
       `(fa-bell (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-bookmark")
       `(fa-bookmark (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-building")
       `(fa-building (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-calendar-alt")
       `(fa-calendar-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-calendar-check")
       `(fa-calendar-check (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-calendar-days")
       `(fa-calendar-days (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-calendar-minus")
       `(fa-calendar-minus (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-calendar-plus")
       `(fa-calendar-plus (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-calendar")
       `(fa-calendar (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-calendar-times")
       `(fa-calendar-times (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-calendar-xmark")
       `(fa-calendar-xmark (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-camera-alt")
       `(fa-camera-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-camera")
       `(fa-camera (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-caret-square-down")
       `(fa-caret-square-down (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-caret-square-left")
       `(fa-caret-square-left (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-caret-square-right")
       `(fa-caret-square-right (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-caret-square-up")
       `(fa-caret-square-up (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-chart-bar")
       `(fa-chart-bar (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-check-circle")
       `(fa-check-circle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-check-square")
       `(fa-check-square (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-chess-bishop")
       `(fa-chess-bishop (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-chess-king")
       `(fa-chess-king (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-chess-knight")
       `(fa-chess-knight (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-chess-pawn")
       `(fa-chess-pawn (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-chess-queen")
       `(fa-chess-queen (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-chess-rook")
       `(fa-chess-rook (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-check")
       `(fa-circle-check (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-dot")
       `(fa-circle-dot (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-down")
       `(fa-circle-down (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-left")
       `(fa-circle-left (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-pause")
       `(fa-circle-pause (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-play")
       `(fa-circle-play (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-question")
       `(fa-circle-question (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-right")
       `(fa-circle-right (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-stop")
       `(fa-circle-stop (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle")
       `(fa-circle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-up")
       `(fa-circle-up (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-user")
       `(fa-circle-user (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-circle-xmark")
       `(fa-circle-xmark (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-clipboard")
       `(fa-clipboard (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-clock-four")
       `(fa-clock-four (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-clock")
       `(fa-clock (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-clone")
       `(fa-clone (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-closed-captioning")
       `(fa-closed-captioning (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-cloud")
       `(fa-cloud (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-comment-alt")
       `(fa-comment-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-comment-dots")
       `(fa-comment-dots (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-commenting")
       `(fa-commenting (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-comments")
       `(fa-comments (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-comment")
       `(fa-comment (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-compass")
       `(fa-compass (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-contact-book")
       `(fa-contact-book (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-contact-card")
       `(fa-contact-card (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-copyright")
       `(fa-copyright (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-copy")
       `(fa-copy (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-credit-card-alt")
       `(fa-credit-card-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-credit-card")
       `(fa-credit-card (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-dizzy")
       `(fa-dizzy (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-dot-circle")
       `(fa-dot-circle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-drivers-license")
       `(fa-drivers-license (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-edit")
       `(fa-edit (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-envelope-open")
       `(fa-envelope-open (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-envelope")
       `(fa-envelope (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-eye-slash")
       `(fa-eye-slash (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-eye")
       `(fa-eye (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-angry")
       `(fa-face-angry (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-dizzy")
       `(fa-face-dizzy (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-flushed")
       `(fa-face-flushed (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-frown-open")
       `(fa-face-frown-open (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-frown")
       `(fa-face-frown (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grimace")
       `(fa-face-grimace (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-beam")
       `(fa-face-grin-beam (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-beam-sweat")
       `(fa-face-grin-beam-sweat (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-hearts")
       `(fa-face-grin-hearts (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-squint")
       `(fa-face-grin-squint (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-squint-tears")
       `(fa-face-grin-squint-tears (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-stars")
       `(fa-face-grin-stars (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin")
       `(fa-face-grin (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-tears")
       `(fa-face-grin-tears (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-tongue-squint")
       `(fa-face-grin-tongue-squint (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-tongue")
       `(fa-face-grin-tongue (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-tongue-wink")
       `(fa-face-grin-tongue-wink (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-wide")
       `(fa-face-grin-wide (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-grin-wink")
       `(fa-face-grin-wink (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-kiss-beam")
       `(fa-face-kiss-beam (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-kiss")
       `(fa-face-kiss (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-kiss-wink-heart")
       `(fa-face-kiss-wink-heart (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-laugh-beam")
       `(fa-face-laugh-beam (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-laugh-squint")
       `(fa-face-laugh-squint (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-laugh")
       `(fa-face-laugh (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-laugh-wink")
       `(fa-face-laugh-wink (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-meh-blank")
       `(fa-face-meh-blank (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-meh")
       `(fa-face-meh (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-rolling-eyes")
       `(fa-face-rolling-eyes (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-sad-cry")
       `(fa-face-sad-cry (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-sad-tear")
       `(fa-face-sad-tear (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-smile-beam")
       `(fa-face-smile-beam (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-smile")
       `(fa-face-smile (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-smile-wink")
       `(fa-face-smile-wink (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-surprise")
       `(fa-face-surprise (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-face-tired")
       `(fa-face-tired (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-alt")
       `(fa-file-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-archive")
       `(fa-file-archive (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-audio")
       `(fa-file-audio (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-clipboard")
       `(fa-file-clipboard (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-code")
       `(fa-file-code (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-excel")
       `(fa-file-excel (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-image")
       `(fa-file-image (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-lines")
       `(fa-file-lines (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-pdf")
       `(fa-file-pdf (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-powerpoint")
       `(fa-file-powerpoint (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file")
       `(fa-file (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-text")
       `(fa-file-text (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-video")
       `(fa-file-video (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-word")
       `(fa-file-word (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-file-zipper")
       `(fa-file-zipper (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-flag")
       `(fa-flag (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-floppy-disk")
       `(fa-floppy-disk (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-flushed")
       `(fa-flushed (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-folder-blank")
       `(fa-folder-blank (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-folder-closed")
       `(fa-folder-closed (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-folder-open")
       `(fa-folder-open (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-folder")
       `(fa-folder (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-font-awesome-flag")
       `(fa-font-awesome-flag (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-font-awesome-logo-full")
       `(fa-font-awesome-logo-full (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-font-awesome")
       `(fa-font-awesome (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-frown-open")
       `(fa-frown-open (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-frown")
       `(fa-frown (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-futbol-ball")
       `(fa-futbol-ball (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-futbol")
       `(fa-futbol (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-gem")
       `(fa-gem (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grimace")
       `(fa-grimace (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-alt")
       `(fa-grin-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-beam")
       `(fa-grin-beam (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-beam-sweat")
       `(fa-grin-beam-sweat (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-hearts")
       `(fa-grin-hearts (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-squint")
       `(fa-grin-squint (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-squint-tears")
       `(fa-grin-squint-tears (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-stars")
       `(fa-grin-stars (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin")
       `(fa-grin (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-tears")
       `(fa-grin-tears (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-tongue-squint")
       `(fa-grin-tongue-squint (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-tongue")
       `(fa-grin-tongue (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-tongue-wink")
       `(fa-grin-tongue-wink (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-grin-wink")
       `(fa-grin-wink (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-back-fist")
       `(fa-hand-back-fist (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-lizard")
       `(fa-hand-lizard (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-paper")
       `(fa-hand-paper (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-peace")
       `(fa-hand-peace (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-point-down")
       `(fa-hand-point-down (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-pointer")
       `(fa-hand-pointer (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-point-left")
       `(fa-hand-point-left (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-point-right")
       `(fa-hand-point-right (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-point-up")
       `(fa-hand-point-up (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-rock")
       `(fa-hand-rock (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-scissors")
       `(fa-hand-scissors (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-handshake-alt")
       `(fa-handshake-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-handshake-simple")
       `(fa-handshake-simple (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-handshake")
       `(fa-handshake (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand-spock")
       `(fa-hand-spock (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hand")
       `(fa-hand (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hard-drive")
       `(fa-hard-drive (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hdd")
       `(fa-hdd (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-headphones-alt")
       `(fa-headphones-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-headphones-simple")
       `(fa-headphones-simple (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-headphones")
       `(fa-headphones (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-heart")
       `(fa-heart (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-home-alt")
       `(fa-home-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-home-lg-alt")
       `(fa-home-lg-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-home")
       `(fa-home (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hospital-alt")
       `(fa-hospital-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hospital")
       `(fa-hospital (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hospital-wide")
       `(fa-hospital-wide (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hourglass-2")
       `(fa-hourglass-2 (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hourglass-empty")
       `(fa-hourglass-empty (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hourglass-half")
       `(fa-hourglass-half (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-hourglass")
       `(fa-hourglass (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-house")
       `(fa-house (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-id-badge")
       `(fa-id-badge (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-id-card")
       `(fa-id-card (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-images")
       `(fa-images (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-image")
       `(fa-image (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-keyboard")
       `(fa-keyboard (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-kiss-beam")
       `(fa-kiss-beam (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-kiss")
       `(fa-kiss (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-kiss-wink-heart")
       `(fa-kiss-wink-heart (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-laugh-beam")
       `(fa-laugh-beam (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-laugh-squint")
       `(fa-laugh-squint (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-laugh")
       `(fa-laugh (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-laugh-wink")
       `(fa-laugh-wink (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-lemon")
       `(fa-lemon (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-life-ring")
       `(fa-life-ring (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-lightbulb")
       `(fa-lightbulb (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-list-alt")
       `(fa-list-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-map")
       `(fa-map (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-meh-blank")
       `(fa-meh-blank (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-meh-rolling-eyes")
       `(fa-meh-rolling-eyes (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-meh")
       `(fa-meh (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-message")
       `(fa-message (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-minus-square")
       `(fa-minus-square (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-money-bill-1")
       `(fa-money-bill-1 (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-money-bill-alt")
       `(fa-money-bill-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-moon")
       `(fa-moon (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-newspaper")
       `(fa-newspaper (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-note-sticky")
       `(fa-note-sticky (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-object-group")
       `(fa-object-group (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-object-ungroup")
       `(fa-object-ungroup (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-paper-plane")
       `(fa-paper-plane (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-paste")
       `(fa-paste (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-pause-circle")
       `(fa-pause-circle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-pen-to-square")
       `(fa-pen-to-square (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-play-circle")
       `(fa-play-circle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-plus-square")
       `(fa-plus-square (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-question-circle")
       `(fa-question-circle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-rectangle-list")
       `(fa-rectangle-list (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-rectangle-times")
       `(fa-rectangle-times (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-rectangle-xmark")
       `(fa-rectangle-xmark (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-registered")
       `(fa-registered (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-sad-cry")
       `(fa-sad-cry (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-sad-tear")
       `(fa-sad-tear (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-save")
       `(fa-save (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-share-from-square")
       `(fa-share-from-square (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-share-square")
       `(fa-share-square (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-smile-beam")
       `(fa-smile-beam (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-smile")
       `(fa-smile (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-smile-wink")
       `(fa-smile-wink (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-snowflake")
       `(fa-snowflake (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-soccer-ball")
       `(fa-soccer-ball (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-square-caret-down")
       `(fa-square-caret-down (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-square-caret-left")
       `(fa-square-caret-left (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-square-caret-right")
       `(fa-square-caret-right (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-square-caret-up")
       `(fa-square-caret-up (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-square-check")
       `(fa-square-check (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-square-full")
       `(fa-square-full (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-square-minus")
       `(fa-square-minus (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-square-plus")
       `(fa-square-plus (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-square")
       `(fa-square (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-star-half-alt")
       `(fa-star-half-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-star-half-stroke")
       `(fa-star-half-stroke (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-star-half")
       `(fa-star-half (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-star")
       `(fa-star (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-sticky-note")
       `(fa-sticky-note (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-stop-circle")
       `(fa-stop-circle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-sun")
       `(fa-sun (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-surprise")
       `(fa-surprise (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-thumbs-down")
       `(fa-thumbs-down (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-thumbs-up")
       `(fa-thumbs-up (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-times-circle")
       `(fa-times-circle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-times-rectangle")
       `(fa-times-rectangle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-tired")
       `(fa-tired (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-trash-alt")
       `(fa-trash-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-trash-can")
       `(fa-trash-can (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-truck")
       `(fa-truck (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-user-alt")
       `(fa-user-alt (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-user-circle")
       `(fa-user-circle (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-user-large")
       `(fa-user-large (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-user")
       `(fa-user (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-vcard")
       `(fa-vcard (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-window-close")
       `(fa-window-close (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-window-maximize")
       `(fa-window-maximize (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-window-minimize")
       `(fa-window-minimize (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-window-restore")
       `(fa-window-restore (@ (color ,color) (width ,dim) (height ,dim))))
      ((string= value "fa-xmark-circle")
       `(fa-xmark-circle (@ (color ,color) (width ,dim) (height ,dim))))
      (t nil))))
    (if onclick
        `(:span (@ (onclick ,onclick) (style "display:inline-flex;cursor:pointer;"))
           ,inner)
        inner)))
